# Generated by Django 3.0.5 on 2020-04-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=200)),
                ('environment', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Root Category Name', max_length=30, verbose_name='Category Name')),
                ('category_type', models.CharField(choices=[('articles', 'Articles'), ('articles/category', 'Article Classification')], help_text='Used to configure route ', max_length=30, verbose_name='Category Type ')),
                ('desc', models.TextField(blank=True, help_text='category description', null=True, verbose_name='decription')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='comment/category/image/%Y/%m')),
                ('category_level', models.CharField(choices=[('1', 'level1'), ('2', 'level2'), ('3', 'level3')], help_text='level', max_length=20, verbose_name='类目级别')),
                ('is_active', models.BooleanField(default=True, help_text='Active', verbose_name='Active Status')),
                ('is_tab', models.BooleanField(default=True, help_text='Tab', verbose_name='Tab Status')),
                ('index', models.IntegerField(default=0, help_text='.', verbose_name='indexing')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='When was added', verbose_name='Add Time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='root.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Classfication',
                'verbose_name_plural': 'Classficationlist',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('en_name', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('en_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#878D99', '灰色'), ('#409EFF', '蓝色'), ('#67C23A', '绿色'), ('#EB9E05', '黄色'), ('#FA5555', '红色')], default='blue', max_length=20)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/master/image/%y/%m')),
                ('url', models.URLField()),
                ('experience', models.FloatField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('post_type', models.CharField(blank=True, choices=[('article', 'article')], max_length=20, null=True)),
                ('click_num', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='post/image/%y/%m')),
                ('front_image_type', models.CharField(choices=[('0', 'small'), ('1', 'medium'), ('2', 'collection')], default='0', max_length=20)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_recommend', models.BooleanField(default=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_commentable', models.BooleanField(default=True)),
                ('browse_password', models.CharField(blank=True, max_length=20, null=True)),
                ('browse_password_encrypt', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.Category')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.License')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/social/image/%y/%m')),
                ('url', models.URLField()),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.PostBaseInfo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='tags',
            field=models.ManyToManyField(through='root.PostTag', to='root.Tag'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('en_title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('en_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/picture/image/%Y/%m')),
                ('link', models.URLField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/banner/image/%y/%m')),
                ('url', models.URLField()),
                ('index', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='root.Category')),
            ],
        ),
    ]
