# Generated by Django 3.0.5 on 2020-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='en_desc',
        ),
        migrations.RemoveField(
            model_name='license',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='en_desc',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='en_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_level',
            field=models.CharField(choices=[('1', 'level1'), ('2', 'level2'), ('3', 'level3')], help_text='level', max_length=20),
        ),
    ]
